package calibre

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	_ "modernc.org/sqlite"
)

// calibreSchema is the subset of Calibre's schema this package reads,
// written out here rather than shipped as a binary fixture: a fixture
// would have to be regenerated by hand to test a Calibre version that
// dropped a table, which is the case that matters most.
const calibreSchema = `
CREATE TABLE books (
	id INTEGER PRIMARY KEY,
	title TEXT NOT NULL DEFAULT 'Unknown',
	sort TEXT,
	timestamp TIMESTAMP,
	pubdate TIMESTAMP,
	series_index REAL NOT NULL DEFAULT 1.0,
	path TEXT NOT NULL DEFAULT '',
	has_cover BOOL DEFAULT 0,
	last_modified TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:00+00:00'
);
CREATE TABLE data (
	id INTEGER PRIMARY KEY,
	book INTEGER NOT NULL,
	format TEXT NOT NULL,
	uncompressed_size INTEGER NOT NULL,
	name TEXT NOT NULL
);
CREATE TABLE authors (
	id INTEGER PRIMARY KEY, name TEXT NOT NULL, sort TEXT);
CREATE TABLE books_authors_link (
	id INTEGER PRIMARY KEY, book INTEGER NOT NULL, author INTEGER NOT NULL);
CREATE TABLE series (id INTEGER PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE books_series_link (
	id INTEGER PRIMARY KEY, book INTEGER NOT NULL, series INTEGER NOT NULL);
CREATE TABLE publishers (id INTEGER PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE books_publishers_link (
	id INTEGER PRIMARY KEY, book INTEGER NOT NULL, publisher INTEGER NOT NULL);
CREATE TABLE tags (id INTEGER PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE books_tags_link (
	id INTEGER PRIMARY KEY, book INTEGER NOT NULL, tag INTEGER NOT NULL);
CREATE TABLE languages (id INTEGER PRIMARY KEY, lang_code TEXT NOT NULL);
CREATE TABLE books_languages_link (
	id INTEGER PRIMARY KEY, book INTEGER NOT NULL,
	lang_code INTEGER NOT NULL, item_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE comments (
	id INTEGER PRIMARY KEY, book INTEGER NOT NULL, text TEXT NOT NULL);
CREATE TABLE identifiers (
	id INTEGER PRIMARY KEY, book INTEGER NOT NULL,
	type TEXT NOT NULL DEFAULT 'isbn', val TEXT NOT NULL);
`

// writeCalibre builds a two-book library: one plain, one with two
// authors in a deliberate order, a series, two formats and identifiers.
func writeCalibre(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	db := openWritable(t, filepath.Join(root, MetadataDB))
	exec(t, db, calibreSchema)

	exec(t, db, `INSERT INTO books
		(id, title, sort, timestamp, pubdate, series_index, path,
		 has_cover, last_modified)
		VALUES
		(1, 'Small Gods', 'Small Gods', '2020-01-02 03:04:05+00:00',
		 '1992-05-01 00:00:00+00:00', 1.0, 'Terry Pratchett/Small Gods (1)',
		 1, '2021-01-01 00:00:00+00:00'),
		(2, 'Good Omens', 'Good Omens', '2020-02-02 03:04:05+00:00',
		 '1990-05-01 00:00:00+00:00', 3.5,
		 'Terry Pratchett/Good Omens (2)', 0,
		 '2022-02-02 00:00:00+00:00')`)
	exec(t, db, `INSERT INTO data (id, book, format, uncompressed_size, name)
		VALUES (1, 1, 'EPUB', 1024, 'Small Gods - Terry Pratchett'),
		       (2, 2, 'EPUB', 2048, 'Good Omens'),
		       (3, 2, 'MOBI', 4096, 'Good Omens')`)
	exec(t, db, `INSERT INTO authors (id, name) VALUES
		(1, 'Terry Pratchett'), (2, 'Neil Gaiman')`)
	// Book 2 is Pratchett *then* Gaiman, and the link ids say so.
	exec(t, db, `INSERT INTO books_authors_link (id, book, author) VALUES
		(1, 1, 1), (2, 2, 1), (3, 2, 2)`)
	exec(t, db, `INSERT INTO series (id, name) VALUES (1, 'Discworld')`)
	exec(t, db, `INSERT INTO books_series_link (id, book, series)
		VALUES (1, 2, 1)`)
	exec(t, db, `INSERT INTO publishers (id, name) VALUES (1, 'Gollancz')`)
	exec(t, db, `INSERT INTO books_publishers_link (id, book, publisher)
		VALUES (1, 1, 1)`)
	exec(t, db, `INSERT INTO tags (id, name) VALUES
		(1, 'Fantasy'), (2, 'Comedy')`)
	exec(t, db, `INSERT INTO books_tags_link (id, book, tag) VALUES
		(1, 1, 1), (2, 1, 2)`)
	exec(t, db, `INSERT INTO languages (id, lang_code) VALUES (1, 'eng')`)
	exec(t, db, `INSERT INTO books_languages_link
		(id, book, lang_code, item_order) VALUES (1, 1, 1, 0)`)
	exec(t, db, `INSERT INTO comments (id, book, text)
		VALUES (1, 1, 'A novel of Omnia.')`)
	exec(t, db, `INSERT INTO identifiers (id, book, type, val) VALUES
		(1, 2, 'ISBN', '9780060853983'), (2, 2, 'google', 'abc123')`)
	if err := db.Close(); err != nil {
		t.Fatalf("close metadata.db: %v", err)
	}

	writeFile(t, root, "Terry Pratchett/Small Gods (1)/"+
		"Small Gods - Terry Pratchett.epub", "small gods bytes")
	writeFile(t, root, "Terry Pratchett/Small Gods (1)/"+CoverName, "jpegbytes")
	writeFile(t, root, "Terry Pratchett/Good Omens (2)/Good Omens.epub",
		"good omens bytes")
	return root
}

func openWritable(t *testing.T, dsn string) *sql.DB {
	t.Helper()
	db, err := sql.Open("sqlite", dsn)
	if err != nil {
		t.Fatalf("open %s: %v", dsn, err)
	}
	return db
}

func exec(t *testing.T, db *sql.DB, statement string, args ...any) {
	t.Helper()
	if _, err := db.ExecContext(t.Context(), statement, args...); err != nil {
		t.Fatalf("exec: %v\n%s", err, statement)
	}
}

func writeFile(t *testing.T, root, rel, content string) {
	t.Helper()
	full := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", rel, err)
	}
}

func openLibrary(t *testing.T, root string) *Library {
	t.Helper()
	library, err := Open(root)
	if err != nil {
		t.Fatalf("open library: %v", err)
	}
	t.Cleanup(func() { _ = library.Close() })
	return library
}

func TestBooksReadsTheWholeLibrary(t *testing.T) {
	t.Parallel()
	library := openLibrary(t, writeCalibre(t))

	books, err := library.Books(t.Context())
	if err != nil {
		t.Fatalf("books: %v", err)
	}
	if len(books) != 2 {
		t.Fatalf("books = %d, want 2", len(books))
	}

	first := books[0]
	if first.Title != "Small Gods" {
		t.Errorf("title = %q", first.Title)
	}
	if got := first.Authors; len(got) != 1 || got[0] != "Terry Pratchett" {
		t.Errorf("authors = %v", got)
	}
	if first.Publisher != "Gollancz" {
		t.Errorf("publisher = %q", first.Publisher)
	}
	if first.Description != "A novel of Omnia." {
		t.Errorf("description = %q", first.Description)
	}
	if got := SortedTags(first); len(got) != 2 ||
		got[0] != "Comedy" || got[1] != "Fantasy" {
		t.Errorf("tags = %v", got)
	}
	if got := first.Languages; len(got) != 1 || got[0] != "eng" {
		t.Errorf("languages = %v", got)
	}
	if !first.HasCover {
		t.Error("has_cover = false, want true")
	}
	if first.Published == nil || first.Published.Year() != 1992 {
		t.Errorf("published = %v", first.Published)
	}
	if want := "Terry Pratchett/Small Gods (1)/cover.jpg"; first.CoverPath() != want {
		t.Errorf("cover path = %q, want %q", first.CoverPath(), want)
	}

	second := books[1]
	// Author order is Calibre's, not the alphabet's.
	if got := second.Authors; len(got) != 2 ||
		got[0] != "Terry Pratchett" || got[1] != "Neil Gaiman" {
		t.Errorf("authors = %v, want Pratchett then Gaiman", got)
	}
	if second.Series != "Discworld" || second.SeriesIndex != 3.5 {
		t.Errorf("series = %q %v", second.Series, second.SeriesIndex)
	}
	if len(second.Formats) != 2 {
		t.Fatalf("formats = %v, want two", second.Formats)
	}
	readable := second.ReadableFormats()
	if len(readable) != 1 {
		t.Fatalf("readable formats = %v, want just the EPUB", readable)
	}
	if want := "Terry Pratchett/Good Omens (2)/Good Omens.epub"; second.RelativePath(readable[0]) != want {
		t.Errorf("epub path = %q, want %q", second.RelativePath(readable[0]), want)
	}
	// Identifier types are lowercased, so a hand-edited ISBN and
	// Calibre's own isbn are the same key.
	if got := second.Identifiers["isbn"]; got != "9780060853983" {
		t.Errorf("isbn = %q", got)
	}
	if got := second.Identifiers["google"]; got != "abc123" {
		t.Errorf("google = %q", got)
	}
	if second.HasCover {
		t.Error("has_cover = true on a book with no cover")
	}
}

func TestOpenRefusesWhatIsNotACalibreLibrary(t *testing.T) {
	t.Parallel()
	if _, err := Open(t.TempDir()); err == nil {
		t.Fatal("opened a directory with no metadata.db")
	}
}

func TestOpenRefusesASymlinkedMetadataDB(t *testing.T) {
	t.Parallel()
	realDir := writeCalibre(t)
	decoy := t.TempDir()
	if err := os.Symlink(filepath.Join(realDir, MetadataDB),
		filepath.Join(decoy, MetadataDB)); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	_, err := Open(decoy)
	if err == nil {
		t.Fatal("opened a library whose metadata.db is a symlink")
	}
}

func TestOpenTakesADatabaseWithMissingRelations(t *testing.T) {
	t.Parallel()
	// A Calibre version without languages or identifiers costs those
	// fields, not the read.
	root := writeCalibre(t)
	db := openWritable(t, filepath.Join(root, MetadataDB))
	exec(t, db, `DROP TABLE books_languages_link`)
	exec(t, db, `DROP TABLE identifiers`)
	if err := db.Close(); err != nil {
		t.Fatalf("close: %v", err)
	}

	library := openLibrary(t, root)
	books, err := library.Books(t.Context())
	if err != nil {
		t.Fatalf("books: %v", err)
	}
	if len(books) != 2 {
		t.Fatalf("books = %d, want 2", len(books))
	}
	if len(books[0].Languages) != 0 {
		t.Errorf("languages = %v, want none", books[0].Languages)
	}
	if len(books[1].Identifiers) != 0 {
		t.Errorf("identifiers = %v, want none", books[1].Identifiers)
	}
	missing := library.Missing()
	if len(missing) != 2 {
		t.Errorf("missing = %v, want two relations", missing)
	}
}

func TestBooksFailsOnAnUnreadableDatabase(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, root, MetadataDB, "this is not a database")
	library, err := Open(root)
	if err != nil {
		return // Refused at open, which is the better outcome.
	}
	t.Cleanup(func() { _ = library.Close() })
	if _, err := library.Books(t.Context()); err == nil {
		t.Fatal("read books out of a file that is not a database")
	}
}

func TestBooksReadWhileTheDatabaseIsWritten(t *testing.T) {
	t.Parallel()
	root := writeCalibre(t)
	library := openLibrary(t, root)

	writer := openWritable(t, filepath.Join(root, MetadataDB))
	defer writer.Close()
	// WAL is what Calibre runs, and is the reason the change gate reads
	// the inventory instead of stat-ing this file.
	exec(t, writer, `PRAGMA journal_mode=WAL`)

	done := make(chan struct{})
	go func() {
		defer close(done)
		for i := 3; i < 20; i++ {
			_, err := writer.ExecContext(t.Context(),
				`INSERT INTO books (id, title, path, last_modified)
				 VALUES (?, ?, ?, '2023-01-01 00:00:00+00:00')`,
				i, fmt.Sprintf("Book %d", i), fmt.Sprintf("B/%d", i))
			if err != nil {
				return
			}
			time.Sleep(time.Millisecond)
		}
	}()

	deadline := time.Now().Add(5 * time.Second)
	for time.Now().Before(deadline) {
		books, err := library.Books(t.Context())
		if err != nil {
			t.Fatalf("books during a write: %v", err)
		}
		if len(books) < 2 {
			t.Fatalf("books = %d during a write", len(books))
		}
		select {
		case <-done:
			return
		default:
		}
	}
	<-done
}

func TestInventoryDigestMovesOnlyWhenSomethingChanged(t *testing.T) {
	t.Parallel()
	root := writeCalibre(t)
	library := openLibrary(t, root)

	first, err := library.Inventory(t.Context())
	if err != nil {
		t.Fatalf("inventory: %v", err)
	}
	if len(first.Books) != 2 {
		t.Fatalf("inventory books = %d, want 2", len(first.Books))
	}
	if !first.Changed("") {
		t.Error("a library that has never been refreshed reports unchanged")
	}

	again, err := library.Inventory(t.Context())
	if err != nil {
		t.Fatalf("inventory: %v", err)
	}
	if again.Digest != first.Digest {
		t.Fatal("digest moved with nothing changed")
	}
	if again.Changed(first.Digest) {
		t.Error("Changed reports a change with nothing changed")
	}

	// A book edited in Calibre moves last_modified, and nothing else
	// needs to.
	writer := openWritable(t, filepath.Join(root, MetadataDB))
	exec(t, writer, `UPDATE books SET title = 'Small Gods (revised)',
		last_modified = '2024-04-04 00:00:00+00:00' WHERE id = 1`)
	if err := writer.Close(); err != nil {
		t.Fatalf("close: %v", err)
	}

	edited, err := library.Inventory(t.Context())
	if err != nil {
		t.Fatalf("inventory: %v", err)
	}
	if !edited.Changed(first.Digest) {
		t.Error("an edited book left the digest where it was")
	}
}

func TestInventorySeesTheFilesOnDisk(t *testing.T) {
	t.Parallel()
	root := writeCalibre(t)
	library := openLibrary(t, root)

	before, err := library.Inventory(t.Context())
	if err != nil {
		t.Fatalf("inventory: %v", err)
	}
	// Book 2 is listed with a MOBI that was never written, and its
	// absence is part of the inventory rather than an error.
	var absent, present int
	for _, book := range before.Books {
		for _, file := range book.Files {
			if file.Present {
				present++
			} else {
				absent++
			}
		}
	}
	if present == 0 || absent == 0 {
		t.Fatalf("present = %d absent = %d, want both", present, absent)
	}

	// A file replaced on disk with different bytes moves the digest,
	// with metadata.db untouched — the case a stat gate would miss.
	writeFile(t, root, "Terry Pratchett/Good Omens (2)/Good Omens.epub",
		"good omens bytes, but longer this time")
	after, err := library.Inventory(t.Context())
	if err != nil {
		t.Fatalf("inventory: %v", err)
	}
	if !after.Changed(before.Digest) {
		t.Error("a rewritten publication file left the digest alone")
	}

	if ids := after.IDs(); len(ids) != 2 {
		t.Errorf("ids = %v, want two", ids)
	}
}

func TestInventoryNoticesADeletedBook(t *testing.T) {
	t.Parallel()
	root := writeCalibre(t)
	library := openLibrary(t, root)

	before, err := library.Inventory(t.Context())
	if err != nil {
		t.Fatalf("inventory: %v", err)
	}

	writer := openWritable(t, filepath.Join(root, MetadataDB))
	exec(t, writer, `DELETE FROM books WHERE id = 2`)
	exec(t, writer, `DELETE FROM data WHERE book = 2`)
	if err := writer.Close(); err != nil {
		t.Fatalf("close: %v", err)
	}

	after, err := library.Inventory(t.Context())
	if err != nil {
		t.Fatalf("inventory: %v", err)
	}
	if !after.Changed(before.Digest) {
		t.Fatal("a deleted book left the digest alone")
	}
	if _, ok := after.IDs()[2]; ok {
		t.Error("a deleted book is still in the inventory")
	}
}

func TestReadOPFLeavesAClearedValueCleared(t *testing.T) {
	t.Parallel()
	root := writeCalibre(t)
	writeFile(t, root, "Terry Pratchett/Good Omens (2)/"+OPFName, goodOmensOPF)
	library := openLibrary(t, root)

	books, err := library.Books(t.Context())
	if err != nil {
		t.Fatalf("books: %v", err)
	}
	book := books[1]
	if err := library.ReadOPF(t.Context(), &book); err != nil {
		t.Fatalf("read opf: %v", err)
	}

	// This database has comments, publishers and languages tables and
	// simply holds nothing in them for this book, which is Calibre
	// saying the fields are empty. The OPF is older than that edit and
	// does not get to undo it.
	if book.Description != "" {
		t.Errorf("description = %q, want the database's clear", book.Description)
	}
	if len(book.Languages) != 0 {
		t.Errorf("languages = %v, want the database's clear", book.Languages)
	}
	if book.Publisher != "" {
		t.Errorf("publisher = %q, want the database's clear", book.Publisher)
	}
	// And nothing the database did state moves either.
	if book.Title != "Good Omens" {
		t.Errorf("title = %q, want the database's", book.Title)
	}
	if got := book.Authors; len(got) != 2 || got[0] != "Terry Pratchett" {
		t.Errorf("authors = %v, want the database's", got)
	}
	if got := book.Identifiers["isbn"]; got != "9780060853983" {
		t.Errorf("isbn = %q, want the database's", got)
	}
}

func TestReadOPFFillsOnlyWhatTheSchemaLacks(t *testing.T) {
	t.Parallel()
	root := writeCalibre(t)
	writeFile(t, root, "Terry Pratchett/Good Omens (2)/"+OPFName, goodOmensOPF)
	// A Calibre version that does not have these relations at all: the
	// one case the OPF fallback exists for.
	writer := openWritable(t, filepath.Join(root, MetadataDB))
	exec(t, writer, `DROP TABLE comments`)
	exec(t, writer, `DROP TABLE publishers`)
	exec(t, writer, `DROP TABLE languages`)
	if err := writer.Close(); err != nil {
		t.Fatalf("close: %v", err)
	}
	library := openLibrary(t, root)

	books, err := library.Books(t.Context())
	if err != nil {
		t.Fatalf("books: %v", err)
	}
	book := books[1]
	if err := library.ReadOPF(t.Context(), &book); err != nil {
		t.Fatalf("read opf: %v", err)
	}

	if book.Description != "An apocalyptic comedy." {
		t.Errorf("description = %q", book.Description)
	}
	if got := book.Languages; len(got) != 1 || got[0] != "en" {
		t.Errorf("languages = %v", got)
	}
	if book.Publisher != "Workman" {
		t.Errorf("publisher = %q", book.Publisher)
	}
	// The relations that are still there keep their say.
	if book.Title != "Good Omens" {
		t.Errorf("title = %q, want the database's", book.Title)
	}
	if got := book.Authors; len(got) != 2 || got[0] != "Terry Pratchett" {
		t.Errorf("authors = %v, want the database's", got)
	}
	if got := book.Identifiers["isbn"]; got != "9780060853983" {
		t.Errorf("isbn = %q, want the database's", got)
	}
}

func TestReadOPFIsSilentWhenThereIsNone(t *testing.T) {
	t.Parallel()
	library := openLibrary(t, writeCalibre(t))
	books, err := library.Books(t.Context())
	if err != nil {
		t.Fatalf("books: %v", err)
	}
	book := books[0]
	before := book
	if err := library.ReadOPF(t.Context(), &book); err != nil {
		t.Fatalf("read opf: %v", err)
	}
	if book.Title != before.Title || book.Publisher != before.Publisher {
		t.Error("a missing metadata.opf changed the book")
	}
}

func TestOpenIsClosedTwiceWithoutComplaint(t *testing.T) {
	t.Parallel()
	library, err := Open(writeCalibre(t))
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	if err := library.Close(); err != nil {
		t.Fatalf("close: %v", err)
	}
	if err := library.Close(); err != nil {
		t.Fatalf("second close: %v", err)
	}
}

func TestRootIsWhatWasOpened(t *testing.T) {
	t.Parallel()
	root := writeCalibre(t)
	library := openLibrary(t, root)
	if library.Root() != root {
		t.Errorf("root = %q, want %q", library.Root(), root)
	}
}

const goodOmensOPF = `<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="2.0"
         unique-identifier="uuid_id">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/"
            xmlns:opf="http://www.idpf.org/2007/opf">
    <dc:title>Good Omens: an OPF title</dc:title>
    <dc:creator opf:role="aut">Somebody Else</dc:creator>
    <dc:description>An apocalyptic comedy.</dc:description>
    <dc:publisher>Workman</dc:publisher>
    <dc:language>en</dc:language>
    <dc:identifier opf:scheme="ISBN">0000000000000</dc:identifier>
  </metadata>
</package>
`

// TestReadableFormatsPrefersEPUBAndAcceptsKEPUB. A KEPUB is an EPUB
// with Kobo's spans injected, so a book Calibre holds only as a KEPUB
// belongs in the catalog rather than being skipped as unservable. When
// both exist the plain EPUB is preferred, whatever order Calibre lists
// them in.
func TestReadableFormatsPrefersEPUBAndAcceptsKEPUB(t *testing.T) {
	for _, tc := range []struct {
		name    string
		formats []Format
		want    []string
	}{{
		name:    "kepub listed first still yields epub first",
		formats: []Format{{Format: "KEPUB"}, {Format: "EPUB"}},
		want:    []string{"EPUB", "KEPUB"},
	}, {
		name:    "kepub only is readable",
		formats: []Format{{Format: "KEPUB"}},
		want:    []string{"KEPUB"},
	}, {
		name:    "lowercase in the database is the same format",
		formats: []Format{{Format: "kepub"}},
		want:    []string{"kepub"},
	}, {
		name:    "formats this server cannot serve are not offered",
		formats: []Format{{Format: "MOBI"}, {Format: "PDF"}, {Format: "AZW3"}},
		want:    nil,
	}, {
		name:    "a book with no formats at all",
		formats: nil,
		want:    nil,
	}} {
		t.Run(tc.name, func(t *testing.T) {
			got := Book{Formats: tc.formats}.ReadableFormats()
			if len(got) != len(tc.want) {
				t.Fatalf("readable = %v, want %v", got, tc.want)
			}
			for i, f := range got {
				if f.Format != tc.want[i] {
					t.Errorf("readable[%d] = %q, want %q", i, f.Format, tc.want[i])
				}
			}
		})
	}
}
