import { build } from "esbuild";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { update } from "./framepool.js";

const root = path.dirname(fileURLToPath(import.meta.url));
const output = path.resolve(root, "../../internal/webui/static/vendor/readium");
await mkdir(output, { recursive: true });
await build({
  absWorkingDir: root,
  entryPoints: ["index.js"],
  outfile: path.join(output, "readium.js"),
  bundle: true,
  format: "esm",
  target: ["es2022"],
  minify: true,
  legalComments: "eof",
  plugins: [{
    name: "reader-script-nonce",
    setup(build) {
      build.onResolve({ filter: /^liseur-reader-nonce$/ }, () => ({ path: path.join(root, "nonce.js") }));
      build.onLoad({ filter: /@readium\/navigator\/dist\/injection\/Injector\.js$/ }, async ({ path: filename }) => {
        const source = await readFile(filename, "utf8");
        // Pinned Readium 2.8.2 patch. Never stamp publisher-supplied elements:
        // this is the factory which creates the engine's own script elements.
        const needle = 'const r=s.createElement("script");';
        if (source.split(needle).length !== 2) throw Error("Readium nonce patch needs review");
        return {
          contents: 'import {scriptNonce} from "liseur-reader-nonce";\n' + source.replace(needle, needle + 'r.setAttribute("nonce",scriptNonce);'),
          loader: "js",
        };
      });
      // Pinned Readium 2.8.2 patch. Neither pool manager frees a frame's own
      // blob (the built HTML document) once a chapter falls out of the
      // pool's live window (update()'s own pruning only marks the entry;
      // the blob itself is freed lazily, the next time that href happens to
      // be revisited) — an evict(href) the reader can call once it decides
      // a chapter is unlikely to be revisited soon. It refuses to touch an
      // href still in the pool (visible or preloaded), matching what the
      // managers' own pruning already treats as untouchable.
      //
      // The same module also gets its update() replaced by the one in
      // framepool.js, which keeps the neighbouring chapters built as hidden
      // frames and shows the current one without waiting for them (see
      // that file). destroy() raises the `closed` flag those background
      // builds check, so none of them attaches a frame to a torn-down pool.
      build.onLoad({ filter: /@readium\/navigator\/dist\/epub\/frame\/FramePoolManager\.js$/ }, async ({ path: filename }) => {
        let source = await readFile(filename, "utf8");
        const once = (needle, what) => {
          if (source.split(needle).length !== 2) throw Error(`Readium FramePoolManager ${what} patch needs review`);
        };
        once('import y from"./FrameBlobBuilder.js";import{FrameManager as P}from"./FrameManager.js";const b=5,m=3;', "update");
        const start = "async update(e,r,s,n=!1){", end = "setCSSProperties(e){";
        once(start, "update");
        once(end, "update");
        const replacement = update.toString().replace(/^async function update\(/, "async update(");
        if (replacement === update.toString()) throw Error("framepool.js update() has an unexpected shape");
        source = source.slice(0, source.indexOf(start)) + replacement + source.slice(source.indexOf(end));
        once("async destroy(){", "destroy");
        source = source.replace("async destroy(){", "async destroy(){this.closed=!0;");
        const needle = "}}export{B as FramePoolManager};";
        once(needle, "evict");
        return {
          contents: source.replace(needle,
            "}evict(e){if(this.pool.has(e)||this.building?.has(e))return;const r=this.blobs.get(e);" +
            "r&&(this.injector?.releaseBlobUrl?.(r),URL.revokeObjectURL(r),this.blobs.delete(e),this.pendingUpdates?.delete(e))}" +
            "}export{B as FramePoolManager};"),
          loader: "js",
        };
      });
      build.onLoad({ filter: /@readium\/navigator\/dist\/epub\/fxl\/FXLFramePoolManager\.js$/ }, async ({ path: filename }) => {
        const source = await readFile(filename, "utf8");
        const needle = "}}export{z as FXLFramePoolManager};";
        if (source.split(needle).length !== 2) throw Error("Readium FXLFramePoolManager evict patch needs review");
        return {
          contents: source.replace(needle,
            "}evict(e){if(this.pool.has(e))return;const r=this.blobs.get(e);r&&(URL.revokeObjectURL(r),this.blobs.delete(e))}" +
            "}export{z as FXLFramePoolManager};"),
          loader: "js",
        };
      });
    },
  }],
});
const packages = ["@readium/navigator", "@readium/shared", "@readium/navigator-html-injectables", "@readium/helpers", "@readium/decorator", "css-tree", "mdn-data", "source-map-js"];
let notices = "Generated by tools/reader/build.mjs. Dependency versions are pinned in package-lock.json.\n";
for (const name of packages) {
  const dir = path.join(root, "node_modules", name);
  const pkg = JSON.parse(await readFile(path.join(dir, "package.json"), "utf8"));
  let license = "";
  for (const file of ["LICENSE", "LICENSE.txt", "LICENSE.md", "license"]) {
    try { license = await readFile(path.join(dir, file), "utf8"); break; } catch {}
  }
  // The toolkit packages share the repository license; two npm packages
  // omit it from their file lists.
  if (!license && name.startsWith("@readium/")) license = await readFile(path.join(root, "node_modules/@readium/navigator/LICENSE"), "utf8");
  if (!license) throw Error("Missing license for " + name);
  notices += `\n${name} ${pkg.version}\n${license}\n`;
}
notices += "\nApproximate string matching (Readium vendored dependency)\n" + await readFile(path.join(root, "node_modules/@readium/navigator-html-injectables/src/vendor/approx-string-match/LICENSE"), "utf8");
await writeFile(path.join(output, "LICENSES.txt"), notices);
