import { build } from "esbuild";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(fileURLToPath(import.meta.url));
const output = path.resolve(root, "../../internal/webui/static/vendor/readium");
await mkdir(output, { recursive: true });
await build({
  absWorkingDir: root,
  entryPoints: ["index.js"],
  outfile: path.join(output, "readium.js"),
  bundle: true,
  format: "esm",
  target: ["es2022"],
  minify: true,
  legalComments: "eof",
  plugins: [{
    name: "reader-script-nonce",
    setup(build) {
      build.onResolve({ filter: /^liseur-reader-nonce$/ }, () => ({ path: path.join(root, "nonce.js") }));
      build.onLoad({ filter: /@readium\/navigator\/dist\/injection\/Injector\.js$/ }, async ({ path: filename }) => {
        const source = await readFile(filename, "utf8");
        // Pinned Readium 2.8.2 patch. Never stamp publisher-supplied elements:
        // this is the factory which creates the engine's own script elements.
        const needle = 'const r=s.createElement("script");';
        if (source.split(needle).length !== 2) throw Error("Readium nonce patch needs review");
        return {
          contents: 'import {scriptNonce} from "liseur-reader-nonce";\n' + source.replace(needle, needle + 'r.setAttribute("nonce",scriptNonce);'),
          loader: "js",
        };
      });
    },
  }],
});
const packages = ["@readium/navigator", "@readium/shared", "@readium/navigator-html-injectables", "@readium/helpers", "@readium/decorator", "css-tree", "mdn-data", "source-map-js"];
let notices = "Generated by tools/reader/build.mjs. Dependency versions are pinned in package-lock.json.\n";
for (const name of packages) {
  const dir = path.join(root, "node_modules", name);
  const pkg = JSON.parse(await readFile(path.join(dir, "package.json"), "utf8"));
  let license = "";
  for (const file of ["LICENSE", "LICENSE.txt", "LICENSE.md", "license"]) {
    try { license = await readFile(path.join(dir, file), "utf8"); break; } catch {}
  }
  // The toolkit packages share the repository license; two npm packages
  // omit it from their file lists.
  if (!license && name.startsWith("@readium/")) license = await readFile(path.join(root, "node_modules/@readium/navigator/LICENSE"), "utf8");
  if (!license) throw Error("Missing license for " + name);
  notices += `\n${name} ${pkg.version}\n${license}\n`;
}
notices += "\nApproximate string matching (Readium vendored dependency)\n" + await readFile(path.join(root, "node_modules/@readium/navigator-html-injectables/src/vendor/approx-string-match/LICENSE"), "utf8");
await writeFile(path.join(output, "LICENSES.txt"), notices);
